title: Nic McDonald
subtitle: Software and Hardware Engineer
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: https://www.nicm.dev    # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
  - text: CV
    url: /assets/pubs/nicmcdonald_cv.pdf
#    - text: Home
#      url: /
#    - text: About
#      url: /about
#    - text: Blog
#      url: /blog
#    - text: Gallery
#      url: /gallery
#    - text: Shop
#      url : /shop
#    - text: Contact
#      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile2.png
author: Nic McDonald
author_bio: I am a computer architecture research scientist and software/hardware engineer. I am a senior research scientist at NVIDIA Research working on next generation hardware and software systems for NVIDIA networks.
author_email: "n.mcdonald83@gmail.com"
author_location: Salt Lake City, Utah, USA
author_website_url: "https://www.nicm.dev"
typewrite-text: Hello! My name is Nic. I'm a computer nerd. Nice to meet you :)
hero_cover_img: sample_cover.jpg # cover.png

# Experiences
author_work_experiences:
  - company_name: NVIDIA
    company_logo: nvidia.png
    company_url: https://nvidia.com
    designation: Research Scientist
    description: Designing next generation large-scale networked systems for Artificial Intelligence (AI) and High Performance Computing (HPC).
    visibility: true
  - company_name: Google
    company_logo: google.png
    company_url: https://google.com
    designation: Software Engineer
    description: Worked in the system infrastructure team specifically on tightly-coupled high-performance network technologies including topologies, routing algorithms, network acceleration and offloading, congestion control, processing architectures, and more.
    visibility: true
  - company_name: Hewlett Packard Labs
    company_logo: hpe.png
    company_url: https://hpe.com/labs
    designation: Research Scientist
    description: A lead architect for a new high-performance network design for large-scale high-performance computing (HPC) systems and massively parallel memory-driven computing (MDC) systems. I was the key designer of the Gen-Z routing architectural specification. Using a data-driven simulation approach I guided the design of a novel multi-chip module (MCM) switch architecture that utilizes co-packaged integrated photonics.
    visibility: true
  - company_name: L3 Communications
    company_logo: l3.png
    company_url: https://l3harris.com
    designation: Digital Hardware Design Engineer
    description: Developed digital processing architectures for encryption, networking, and waveform data processing. Designed systems with strict requirements for high-performance, low-power, and low-area. All designs were meticulously scrutinized for high-reliability and signal integrity.
    visibility: true

# Education
author_education_details:
- college_logo: stanford.png
  college_name: Stanford University
  college_url: https://stanford.edu
  college_degree: Doctorate of Philosophy
  description: Electrical Engineering, 2016
  visibility: true
- college_logo: uou.png
  college_name: University of Utah
  college_url: https://utah.edu
  college_degree: Master's
  description: Electrical Engineering, 2012
  visibility: true
- college_logo: uou.png
  college_name: University of Utah
  college_url: https://utah.edu
  college_degree: Bachelor's
  description: Computer Engineering, 2010
  visibility: true


# Projects
author_project_details:
- project_thumbnail: libdes.png
  project_title: Libdes
  project_description: A parallel discrete event simulation framework.
  project_url: https://github.com/nicmcd/libdes
  visibility: true

- project_thumbnail: supersim.png
  project_title: SuperSim
  project_description: A flit-level interconnection network simulator.
  project_url: https://github.com/nicmcd/supersim
  visibility: true

- project_thumbnail: paramgmt.jpg
  project_title: ParaMgmt
  project_description: A parallel SSH-based remote machine management system.
  project_url: https://github.com/google/paramgmt
  visibility: true

- project_thumbnail: taskrun.png
  project_title: TaskRun
  project_description: An easy-to-use python package for parallel task execution.
  project_url: https://github.com/nicmcd/taskrun
  visibility: true

- project_thumbnail: devsearch.png
  project_title: DevSearch
  project_description: A project development find and goto system.
  project_url: https://github.com/nicmcd/devsearch
  visibility: true

# Publications
author_publication_details:
- publication_title: Practical and Efficient Incremental Adaptive Routing for HyperX Networks
  publication_summary: We present two practical and efficient incremental adaptive routing algorithms for HyperX.
  publication_authors: Nic McDonald, Mikhail Isaev, Adriana Flores, Al Davis, John Kim
  publication_pdf: pubs/nicmcdonald_hxrouting_sc_2019.pdf
  publication_slides: pubs/nicmcdonald_hxrouting_sc_2019_slides.pdf
  publication_cite: pubs/nicmcdonald_hxrouting_sc_2019.bib
  publication_doi: https://doi.org/10.1145/3295500.3356151

- publication_title: "SuperSim: Extensible Flit-Level Simulation of Large-Scale Interconnection Networks"
  publication_summary: We present SuperSim, an open-source flit-level interconnection network simulator for large-scale high-performance networks.
  publication_authors: Nic McDonald, Adriana Flores, Al Davis, Mikhail Isaev, John Kim, Doug Gibson
  publication_pdf: nicmcdonald_supersim_ispass_2018.pdf
  publication_slides: nicmcdonald_supersim_ispass_2018_slides.pdf
  publication_cite: nicmcdonald_supersim_ispass_2018.bib
  publication_doi: https://doi.org/10.1109/ISPASS.2018.00017

- publication_title: High-Performance Service-Oriented Computing
  publication_summary: This dissertation presents Sikker, a highly-scalable high-performance distributed system architecture for secure service-oriented.
  publication_authors: Nic McDonald, Bill Dally
  publication_pdf: nicmcdonald_hpsoc_stanford_2016.pdf
  publication_slides: nicmcdonald_hpsoc_stanford_2016_slides.pdf
  publication_cite: nicmcdonald_hpsoc_stanford_2016.bib
  publication_doi:


#- project_thumbnail: gamershub.png
#  project_title: Gamers Hub
#  project_description: A Platform built for Gamers and Game Devs
#  project_url: https://gamershub.in
#  visibility: true
#- project_thumbnail: hack4r.PNG
#  project_title: Hack4r
#  project_description: A Platform built for Hackers and Penetration Testers
#  project_url: https://hack4r.com
#  visibility: true

# social links - using
github_username:  nicmcd
#bitbucket_username: nicmcd
#facebook_username: johndoe
linkedin_username: nicmcdonald

# social links - not using
#twitter_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: nicmcd

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
